'use client'

import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { formatCurrency } from '@/lib/utils'
import { CheckCircle2, AlertCircle, Loader2, Download } from 'lucide-react'

type TaxData = {
  insurancePremium: number
  preventiveCheckups: number
  seniorCitizenPremium: number
  total80D: number
  selfLimit: number
  seniorLimit: number
  maxDeduction: number
  yearlyExpenses: { date: string; description: string; amount: number; type: string }[]
}

const PREVENTIVE_CATEGORIES = ['diagnostics', 'vaccination']
const CURRENT_FY_START = new Date().getMonth() >= 3
  ? new Date(new Date().getFullYear(), 3, 1)
  : new Date(new Date().getFullYear() - 1, 3, 1)
const CURRENT_FY_END = new Date(CURRENT_FY_START.getFullYear() + 1, 2, 31)
const FY_LABEL = `FY ${CURRENT_FY_START.getFullYear()}–${String(CURRENT_FY_START.getFullYear() + 1).slice(2)}`

export default function TaxCalculator({ userId }: { userId: string }) {
  const [data, setData] = useState<TaxData | null>(null)
  const [loading, setLoading] = useState(true)
  const [hasSenior, setHasSenior] = useState(false)
  const supabase = createClient()

  useEffect(() => { fetchTaxData() }, [hasSenior])

  async function fetchTaxData() {
    setLoading(true)
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return

    const startDate = CURRENT_FY_START.toISOString().split('T')[0]
    const endDate = CURRENT_FY_END.toISOString().split('T')[0]

    const [{ data: expenses }, { data: policies }, { data: members }] = await Promise.all([
      supabase.from('expenses')
        .select('*, expense_categories(name)')
        .eq('user_id', user.id)
        .gte('expense_date', startDate)
        .lte('expense_date', endDate),
      supabase.from('insurance_policies')
        .select('*')
        .eq('user_id', user.id)
        .eq('is_active', true),
      supabase.from('family_members')
        .select('*')
        .eq('user_id', user.id),
    ])

    // Insurance premium (self + family, non-senior)
    const insurancePremium = policies
      ?.filter(p => !p.is_senior)
      ?.reduce((s, p) => {
        if (!p.premium_annual) return s
        const monthsInFY = 12
        return s + Number(p.premium_annual)
      }, 0) ?? 0

    // Preventive health checkups (capped at ₹5,000)
    const preventiveExpenses = expenses?.filter(e => {
      const catName = (e.expense_categories as any)?.name?.toLowerCase() ?? ''
      return PREVENTIVE_CATEGORIES.some(c => catName.includes(c))
    }) ?? []
    const preventiveTotal = preventiveExpenses.reduce((s, e) => s + Number(e.amount), 0)
    const preventiveCheckups = Math.min(preventiveTotal, 5000)

    const selfLimit = 25000
    const seniorLimit = hasSenior ? 50000 : 0
    const selfDeductible = Math.min(insurancePremium + preventiveCheckups, selfLimit)
    const total80D = selfDeductible + seniorLimit
    const maxDeduction = selfLimit + (hasSenior ? 50000 : 0)

    const yearlyExpenses = [
      ...(policies?.map(p => ({
        date: p.created_at?.split('T')[0] ?? '',
        description: `${p.provider_name} — ${p.plan_name ?? 'Health Insurance'}`,
        amount: Number(p.premium_annual ?? 0),
        type: 'Insurance premium',
      })) ?? []),
      ...preventiveExpenses.map(e => ({
        date: e.expense_date,
        description: e.description,
        amount: Number(e.amount),
        type: 'Preventive checkup',
      })),
    ]

    setData({
      insurancePremium,
      preventiveCheckups,
      seniorCitizenPremium: hasSenior ? 50000 : 0,
      total80D,
      selfLimit,
      seniorLimit,
      maxDeduction,
      yearlyExpenses,
    })
    setLoading(false)
  }

  function downloadReport() {
    if (!data) return
    const lines = [
      `SECTION 80D DEDUCTION REPORT — ${FY_LABEL}`,
      `Generated by MediTrack on ${new Date().toLocaleDateString('en-IN')}`,
      '',
      '--- SUMMARY ---',
      `Health insurance premium: ${formatCurrency(data.insurancePremium)}`,
      `Preventive health checkups: ${formatCurrency(data.preventiveCheckups)}`,
      hasSenior ? `Senior citizen parent premium: ${formatCurrency(data.seniorCitizenPremium)}` : '',
      `Total 80D deduction: ${formatCurrency(data.total80D)}`,
      `Maximum allowed: ${formatCurrency(data.maxDeduction)}`,
      '',
      '--- ELIGIBLE EXPENSES ---',
      'Date,Description,Amount,Type',
      ...data.yearlyExpenses.map(e =>
        `"${e.date}","${e.description}","${e.amount}","${e.type}"`
      ),
    ].filter(Boolean)

    const blob = new Blob([lines.join('\n')], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `80D-report-${FY_LABEL.replace(' ', '-')}.csv`
    a.click()
    URL.revokeObjectURL(url)
  }

  if (loading) return (
    <div className="flex items-center justify-center py-8">
      <Loader2 className="w-5 h-5 animate-spin text-muted-foreground" />
    </div>
  )

  if (!data) return null

  const utilizationPct = Math.min(100, Math.round((data.total80D / data.maxDeduction) * 100))
  const taxSaved30 = Math.round(data.total80D * 0.30)
  const taxSaved20 = Math.round(data.total80D * 0.20)

  return (
    <div className="space-y-4">
      {/* FY Label */}
      <div className="flex items-center justify-between">
        <span className="text-xs font-medium text-muted-foreground bg-muted rounded-full px-3 py-1">
          {FY_LABEL} (Apr {CURRENT_FY_START.getFullYear()} – Mar {CURRENT_FY_END.getFullYear()})
        </span>
        <label className="flex items-center gap-2 text-xs cursor-pointer">
          <input type="checkbox" checked={hasSenior} onChange={e => setHasSenior(e.target.checked)} />
          <span className="text-muted-foreground">Include senior citizen parents (₹50,000 extra)</span>
        </label>
      </div>

      {/* Main deduction card */}
      <div className="bg-amber-50 border border-amber-200 rounded-2xl p-5">
        <div className="flex items-center justify-between mb-4">
          <div>
            <div className="text-xs text-amber-600 font-medium mb-1">Total 80D deduction</div>
            <div className="text-3xl font-semibold text-amber-900">
              {formatCurrency(data.total80D)}
            </div>
            <div className="text-xs text-amber-600 mt-1">
              of {formatCurrency(data.maxDeduction)} maximum allowed
            </div>
          </div>
          <div className="text-right">
            <div className="text-xs text-amber-600 mb-1">Estimated tax saved</div>
            <div className="text-sm font-semibold text-amber-800">
              {formatCurrency(taxSaved30)} <span className="font-normal text-amber-600">@ 30%</span>
            </div>
            <div className="text-sm font-semibold text-amber-800">
              {formatCurrency(taxSaved20)} <span className="font-normal text-amber-600">@ 20%</span>
            </div>
          </div>
        </div>

        {/* Progress bar */}
        <div className="h-2 bg-amber-200 rounded-full overflow-hidden">
          <div
            className="h-full bg-amber-500 rounded-full transition-all"
            style={{ width: `${utilizationPct}%` }}
          />
        </div>
        <div className="text-xs text-amber-600 mt-1">{utilizationPct}% of deduction limit used</div>
      </div>

      {/* Breakdown */}
      <div className="grid grid-cols-1 gap-3">
        <div className="flex items-center justify-between py-3 border-b border-border">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-500" />
            <div>
              <div className="text-sm font-medium">Health insurance premiums</div>
              <div className="text-xs text-muted-foreground">Section 80D(a)</div>
            </div>
          </div>
          <div className="text-sm font-semibold">{formatCurrency(data.insurancePremium)}</div>
        </div>

        <div className="flex items-center justify-between py-3 border-b border-border">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-500" />
            <div>
              <div className="text-sm font-medium">Preventive health checkups</div>
              <div className="text-xs text-muted-foreground">Capped at ₹5,000 · Section 80D(b)</div>
            </div>
          </div>
          <div className="text-sm font-semibold">{formatCurrency(data.preventiveCheckups)}</div>
        </div>

        {hasSenior && (
          <div className="flex items-center justify-between py-3 border-b border-border">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-500" />
              <div>
                <div className="text-sm font-medium">Senior citizen parents</div>
                <div className="text-xs text-muted-foreground">Additional ₹50,000 limit</div>
              </div>
            </div>
            <div className="text-sm font-semibold">{formatCurrency(data.seniorCitizenPremium)}</div>
          </div>
        )}

        {data.total80D < data.maxDeduction && (
          <div className="flex items-start gap-2 bg-blue-50 border border-blue-200 rounded-xl px-4 py-3">
            <AlertCircle className="w-4 h-4 text-blue-500 shrink-0 mt-0.5" />
            <div className="text-xs text-blue-800 leading-relaxed">
              You have {formatCurrency(data.maxDeduction - data.total80D)} of unused 80D limit.
              {data.insurancePremium === 0 && ' Add your insurance premium in the Insurance section to claim more.'}
              {data.preventiveCheckups < 5000 && data.insurancePremium > 0 && ` Book preventive checkups (blood tests, eye tests) to use up to ₹${formatCurrency(5000 - data.preventiveCheckups)} more.`}
            </div>
          </div>
        )}
      </div>

      {/* Download */}
      <button onClick={downloadReport}
        className="btn-secondary w-full flex items-center justify-center gap-2 text-sm">
        <Download className="w-4 h-4" />
        Download 80D report for CA / tax filing
      </button>

      <p className="text-xs text-muted-foreground text-center leading-relaxed">
        Based on expenses and insurance data in MediTrack for {FY_LABEL}.
        Consult your CA for final tax computation.
      </p>
    </div>
  )
}